CREATE TABLE IF NOT EXISTS article (
	id INT(11) NOT NULL AUTO_INCREMENT,
	content VARCHAR(50) NULL DEFAULT NULL,
	created DATETIME NULL DEFAULT NULL,
	updated DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (id)
)
;
